### ISSUE TITLE
unable to build final dockerfile.cpu 

### ISSUE THREAD

**Issue by Vertika09** [aws/sagemaker-pytorch-training-toolkit#208]
Command used to build Dockerfile:  docker build -t preprod-pytorch:1.0.0-cpu-py3 -f docker/1.0.0/final/Dockerfile.cpu --build-arg py_version=3 .

Sending build context to Docker daemon  147.1MB
Step 1/11 : ARG py_version
Step 2/11 : FROM pytorch-base:1.1.0-cpu-py$py_version
 ---> 721d122daba2
Step 3/11 : LABEL com.amazonaws.sagemaker.capabilities.accept-bind-to-port=true
 ---> Using cache
 ---> 7a87d543152b
Step 4/11 : COPY lib/changehostname.c /
COPY failed: stat /var/lib/docker/tmp/docker-builder479190093/lib/changehostname.c: no such file or directory

**Comment by ajaykarpur** [comment]
Hi @Vertika09, it looks like the solution here is to copy the contents of build_artifacts to a folder called `lib` inside the build context. Please let us know if that doesn't work and you're still running into issues building the image.

**Comment by Vertika09** [comment]
@ajaykarpur Thanks...will try this

**Comment by marksal87** [comment]
@Vertika09, we ran into this issue today and solved it by moving the contents of the `build_artifacts` folder (`changehostname.c`) to the working directory where we ran the docker command from (one level up from `build_artifacts`. Moving the files to `lib` did not work for us.

**Comment by nadiaya** [comment]
Another approach I would recommend for build older images is using the state of the repo when they were added: https://github.com/aws/sagemaker-pytorch-training-toolkit/tree/cb9f4172f15bdcee5d086723830b369a8d8939cf/docker/1.1.0 

Since we only guarantee that current libraries work with the latest supported framework version.
