### ISSUE TITLE
FastAI v1.0.59 causes failed training job

### ISSUE THREAD

**Issue by dean-cpi** [aws/sagemaker-pytorch-training-toolkit#215]
**Describe the bug**
The fastprogress bar using Fast AI doesn't work correctly with a PyTorch training job.
I got an error TypeError: __init__() got an unexpected keyword argument 'auto_update', when launching a training job. The attached screenshot is what lead me to this error. The error is described here:
https://forums.fast.ai/t/fastprogress-auto-update/58830

**To reproduce**
Launch a training job using fast ai version 1.0.59 (used as default at present).

**Expected behavior**
A successful training job.

**Screenshots or logs**
![image](https://user-images.githubusercontent.com/67267974/86003422-09835100-ba12-11ea-8c6e-92c8e57d05b0.png)

**System information**
A description of your system. Please provide:
- **Toolkit version**: n/a
- **Framework version**: pytorch 1.4.0
- **Python version**: 3
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: N

**Additional context**
This problem should simply require a version increment of fastai to resolve, they've already released the bugfix in 1.0.60.

**Comment by nadiaya** [comment]
This repo no longer manages docker images and external libraries installed in them.
Please file the issue against https://github.com/aws/deep-learning-containers
